---
  - name: Upload tar.gz Elasticsearch from remote URL
    get_url:
      url: "https://sourceforge.net/projects/elasticsearch.mirror/files/v7.17.5/Elasticsearch%20{{ elastic_version }}.tar.gz/download"
      dest: "/tmp/Elasticsearch%20{{ elastic_version }}.tar.gz"
      mode: 0755
      timeout: 60
      force: true
      validate_certs: false
    register: get_elastic
    until: get_elastic is succeeded
    tags: elastic
  - name: Create directrory for Elasticsearch
    file:
      state: directory
      mode: 0644
      path: "{{ elastic_home }}"
    tags: elastic
  - name: Extract Elasticsearch in the installation directory
    become: true
    unarchive:
      copy: false
      src: "/tmp/Elasticsearch%20{{ elastic_version }}.tar.gz"
      dest: "{{ elastic_home }}"
      extra_opts: [--strip-components=1]
      creates: "{{ elastic_home }}/bin/elasticsearch"
    tags:
      - elastic
  - name: Set environment Elastic
    become: true
    template:
      src: templates/elk.sh.j2
      mode: 0644
      dest: /etc/profile.d/elk.sh
    tags: elastic
